version: '3'

services:      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "paulo_alonso_@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    networks:
      - postgres
      
networks: 
  postgres:
    driver: bridge