version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./Volume:/var/lib/postgresql/data 
    networks:
      - postgres
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "paulo_alonso_@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    networks:
      - postgres

networks: 
  postgres:
    driver: bridge
