version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_USER: root
      DB_PASSWORD: mysql
      DB_DATABASE: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8050:8080
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - volume=./volume
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 60s
      retries: 10
