version: '3'
services:
  wildfly:
    image: 'bitnami/wildfly:latest'
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - 'wildfly_data:/bitnami'
    environment:
      - WILDFLY_PASSWORD=123

volumes:
  wildfly_data:
    driver: local